- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Suscription Azure (c584df84-2778-41b6-a949-e7c9e8f3cf8b)'
    appType: 'webApp'
    appName: 'mi-aplicacion-web-test'
    deployToSlotOrASE: true
    resourceGroupName: 'api-gestion-personal_group'
    slotName: 'production'
    package: '$(System.DefaultWorkingDirectory)/**/*.zip'
    deploymentMethod: 'auto'